#pragma once
namespace OBJID
{
	enum OBJ {
		MAP, GATE, PLAYER_FRONT, PLAYER, PLAYER_BULLET, BOMB,
		NORMALMONSTER, SHILEDMONSTER, SWIRLMONSTER, TONADOMONSTER, BOSS, MONSTER_BULLET, EFFECT, UI, END
	};
}
namespace GROUPID
{
	enum ID { BACKGROUND, OBJECT, EFFECT, UI, END };
}